### ISSUE TITLE
BUG | List: types not taking effect - "square", "circle" etc

### ISSUE THREAD

**Issue by hnprashanth** [antstackio/hover-design#104]
## Expected Behavior

"List" was supposed to render shape, ex: square, circle when appropriate "type" is passed in props.

## Current Behavior

Sample Code:

```
import "@hover-design/react/dist/style.css";
import { List, ListItem } from "@hover-design/react";

export default function App() {
  return (
    <div className="App">
      <List type="square">
        <ListItem>One</ListItem>
        <ListItem>Two</ListItem>
      </List>
    </div>
  );
}
```

## Steps to Reproduce (for bugs)

1. Copy the above sample code
2. Try it in CodeSandbox or your local project

## Your Environment

* Version used: 0.1.8
* Browser name and version: Safari 16.0, Chrome 105.0.5195.125
* Operating System and version (desktop or mobile): macOS Monterey 12.6
* Link to your project:

**Comment by pruthvi2103** [comment]
To add to that, list items get wrong classname assigned, fixed in #106
