### ISSUE TITLE
BUG | Divider: "Vertical Divider" unable to produce desired result

### ISSUE THREAD

**Issue by hnprashanth** [antstackio/hover-design#105]
## Expected Behavior

When `orientation="vertical"` prop is passed to the Divider component, it is supposed to render a vertical divider.

## Current Behavior

The component doesn't render a vertical divider. Applies to all vertical divider variations as mentioned in [docs](https://hover.style/docs/components/divider#vertical-divider): 
- Vertical Divider
- Vertical Divider with Label
- Vertical Divider with Custom Label

Screenshot below:
![Screen Shot 2022-09-15 at 12 51 54 PM](https://user-images.githubusercontent.com/379689/190340677-554e4521-1477-434d-9721-f574d6e26a42.png)

Code Snippet:

```
import "@hover-design/react/dist/style.css";
import { Divider } from "@hover-design/react";

export default function App() {
  return (
    <div className="App">
      <span>Label 1</span>
      <Divider orientation="vertical" style={{ margin: "0 10px" }} />
      <span>Label 2</span>
      <Divider orientation="vertical" style={{ margin: "0 10px" }} />
      <span>Label 3</span>
    </div>
  );
}
```

## Steps to Reproduce (for bugs)

1. Copy the above sample code
2. Try it in CodeSandbox or your local project

## Your Environment

* Version used: 0.1.8
* Browser name and version: Safari 16.0
* Operating System and version (desktop or mobile): macOS Monterey 12.6
* Link to your project:

**Comment by pruthvi2103** [comment]
pl refer #109 for more context. Not actually bug with code but. issue with docs not specifying the constraints properly 

cc- @hnprashanth
