### ISSUE TITLE
HOV-47 | TextArea: minlength & maxlength not taking effect

### ISSUE THREAD

**Issue by hnprashanth** [antstackio/hover-design#110]
## Expected Behavior

TextArea should adhere to minlength or maxlength passed through props

## Current Behavior

Using these attributes results in following error:

```
Type '{ placeholder: string; maxlength: number; cols: number; defaultValue: string; }' is not assignable to type 'IntrinsicAttributes & Pick<TextAreaProps, "required" | "key" | "id" | "name" | "color" | "translate" | "value" | "hidden" | "dir" | "form" | ... 260 more ... | "fixedSize"> & RefAttributes<...>'.  
Property 'maxlength' does not exist on type 'IntrinsicAttributes & Pick<TextAreaProps,
```

## Steps to Reproduce (for bugs)

1. Pass either minlength or maxlength prop to <TextArea /> component
2.

## Your Environment

* Version used:  0.1.8
* Browser name and version: Safari 16.0
* Operating System and version (desktop or mobile): macOS Monterey 12.6
* Link to your project:

**Comment by Shadow-Flash** [comment]
@hnprashanth I think you have passed minlength and maxlength but the props are minLength and maxLength --> it's the capital 'L'.
I checked in Google Chrome and Safari as well, In both browsers, it's working.
@Raalzz or @pruthvi2103 anyone of you can re-check again?

**Comment by pruthvi2103** [comment]
@Shadow-Flash @hnprashanth pls confirm if this issue requires anything else, the ticket no is `HOV-47`

**Comment by pruthvi2103** [comment]
tried in codesandbox, the props work. Closing this issue
