### ISSUE TITLE
HOV-45 | Icon Component

### ISSUE THREAD

**Issue by Raalzz** [antstackio/hover-design#113]
## Expected Behavior

Component has some pre-defined props that causes some issues

## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by pruthvi2103** [comment]
ticket code - [HOV-45](https://hoverdesign.atlassian.net/browse/HOV-45)
