### ISSUE TITLE
HOV-10 | Flex Component

### ISSUE THREAD

**Issue by pruthvi2103** [antstackio/hover-design#18]
## Expected Behavior
Make a `<Flex>` Component
Features:
- Should come with default Flex props
- Modify the direction, display, justify, align, etc via props
- Inherit from `<div>`

## Current Behavior

No flex component

**Comment by Shadow-Flash** [comment]
Issued the PR for the same:
https://github.com/antstackio/hover-design/pull/25#issue-1326948869
