### ISSUE TITLE
HOV-26 | Radio Button

### ISSUE THREAD

**Issue by pruthvi2103** [antstackio/hover-design#22]
## Expected Behavior
Make a `<Radio>` Component
Features:
- Should come with default `input` props
- Inherit from `<input>`

## Current Behavior
No radio button component

- [ ] Make spec for radio button
- [ ] Make the base component with API and without styles
- [ ] add styling

**Comment by pruthvi2103** [comment]
relates to #24

**Comment by Rakshith088** [comment]
@pruthvi2103 
https://www.figma.com/file/IZHRiuhZEG4GCIMpBKA7ar/Hover?node-id=1851%3A384
Radio Button Figma link

**Comment by Raalzz** [comment]
Spec for Radio and RadioGroup [V1] :

Radio Spec:

| Attributes |             Values              | Default Value | Optional ? |
| :--------- | :-----------------------------: | :-----------: | ---------: |
| value      |            `string`             |       -       |         No |
| color      |            `string`             |       -       |        Yes |
| label      |            `string`             |       -       |        Yes |
| size       | `xs` `sm` `md` `lg` `xl` number |     `sm`      |        Yes |
| isDisabled |            `boolean`            |    `false`    |        Yes |

RadioGroup Spec:


| Attributes  |             Values              | Default Value  | Optional ? |
| :---------- | :-----------------------------: | :------------: | ---------: |
| children    |        `React.Children`         |       -        |         No |
| orientation |   `"horizontal"` `"vertical"`   | `"horizontal"` |        Yes |
| Spacing     | `xs` `sm` `md` `lg` `xl` number |      `sm`      |        Yes |

**Comment by Raalzz** [comment]
Feedback from @pruthvi2103 :

For RadioGroup:
- Add flex-wrap so that element does not overflow

For Radio:
- Remove the label as a prop
- Add id and name

**Comment by pruthvi2103** [comment]
closed by #85
