### ISSUE TITLE
HOV-29 | Alert Component

### ISSUE THREAD

**Issue by Raalzz** [antstackio/hover-design#32]
## Expected Behavior
Make a `<Alert>` Component
Features:
- Should come with default `div` props
- Inherit from `<div>`

## Current Behavior
No alert component

- [ ] Make spec for alert component
- [ ] Make the base component with API and without styles
- [ ] add styling

**Comment by Rakshith088** [comment]
@pruthvi2103 
Alert Components
https://www.figma.com/file/IZHRiuhZEG4GCIMpBKA7ar/Hover?node-id=1864%3A397

**Comment by pruthvi2103** [comment]
Deprioritizing this for next release removing from https://github.com/antstackio/hover-design/milestone/3

**Comment by pruthvi2103** [comment]
issue code [HOV-29](https://hoverdesign.atlassian.net/browse/HOV-29)

**Comment by saurabhsutar192** [comment]
Alert Specs
| Prop             |       type        | Optional? |
| :--------------- | :---------------: | --------: |
| children  |     `JSX Element`&123;`string`     |       No |
| closeButtonLabel |     `string`     |       Yes |
| color      | `string` |       Yes |
| icon       |     `JSX Element`    |       Yes |
| onClose|     `()=>{}`     |       Yes |
|borderRadius|`string`|Yes|
|title|`string`|Yes|
|variant|`string`|Yes|
|withCloseButton|`boolean`|Yes|
