### ISSUE TITLE
HOV-53 | Tooltip Component

### ISSUE THREAD

**Issue by Raalzz** [antstackio/hover-design#35]
## Expected Behavior
Make a `<Tooltip>` Component
Features:
- Should come with default `div` props
- Inherit from `<div>`

## Current Behavior
No tooltip component

- [ ] Make spec for tooltip component
- [ ] Make the base component with API and without styles
- [ ] add styling

**Comment by pruthvi2103** [comment]
issue code: [HOV-53](https://hoverdesign.atlassian.net/browse/HOV-53)
