### ISSUE TITLE
HOV-52 | Loader Component

### ISSUE THREAD

**Issue by Raalzz** [antstackio/hover-design#37]
## Expected Behavior
Make a `<Loader>` Component
Features:
- Should come with default `div` props
- Inherit from `<div>`

## Current Behavior
No loader component

- [ ] Make spec for loader component
- [ ] Make the base component with API and without styles
- [ ] add styling

**Comment by pruthvi2103** [comment]
Issue Code [HOV-52](https://hoverdesign.atlassian.net/browse/HOV-52)

**Comment by Rakshith088** [comment]
@pruthvi2103 @saurabhsutar192 
Loader Component 
https://www.figma.com/file/IZHRiuhZEG4GCIMpBKA7ar/Hover?node-id=1916%3A411
