### ISSUE TITLE
HOV-30 | NativeSelect component

### ISSUE THREAD

**Issue by Raalzz** [antstackio/hover-design#38]
## Expected Behavior
Make a `<NativeSelect>` Component
Features:
- Should come with default `select` props
- Inherit from `<select>`

## Current Behavior
No NativeSelect component

- [ ] Make spec for NativeSelect component
- [ ] Make the base component with API and without styles
- [ ] add styling

**Comment by saurabhsutar192** [comment]
Spec for nativeSelect :

| Attributes        |              Values               | Default Value | Optional ? |
| :---------------- | :-------------------------------: | :-----------: | ---------: |
| options           |            `Options[]`            |       -       |        Yes |
| value       |            `controlled input value`            |       -       |        Yes |
| defaultValue      | `Uncontrolled input defaultValue` |       -       |        Yes |
| isDisabled        |             `boolean`             |    `false`    |        Yes |
| height    |             `string`             |    `fit-content`    |        Yes |
| roundness          |            `string`            |     `0`       |        Yes |
| placeholder|            `string`            |       -       |        Yes |
| onChange          |     `(value: string) => void`     |       -       |        Yes |
| error   |           `string` | `boolean`            |       -       |        Yes |
