### ISSUE TITLE
HOV-14 | Checkbox Component

### ISSUE THREAD

**Issue by pruthvi2103** [antstackio/hover-design#39]
## Expected Behavior
Make a `<Checkbox>` Component
Features:
- Should come with default `input` props
- Inherit from `<input type="checkbox">`

## Current Behavior
No checkbox component

- [ ] Make spec for modal component
- [ ] Make the base component with API and without styles
- [ ] add styling

**Comment by Rakshith088** [comment]
@pruthvi2103 
Figma Link to Check Box
https://www.figma.com/file/IZHRiuhZEG4GCIMpBKA7ar/Hover?node-id=1707%3A676

**Comment by pruthvi2103** [comment]
Deprioritizing this for next release removing from https://github.com/antstackio/hover-design/milestone/3

**Comment by Raalzz** [comment]
## Checkbox Specs


### Checkbox Props Reference

| Key                 |              type               | Optional? |
| :------------------ | :-----------------------------: | --------: |
| value               |            `string;`            |        No |
| name                |            `string;`            |        No |
| id                  |            `string;`            |        No |
| indeterminate       |           `boolean;`            |        No |
| isDisabled          |            `boolean`            |       Yes |
| checkboxSize        | `xs` `sm` `md` `lg` `xl` string |       Yes |
| borderRadius        | `xs` `sm` `md` `lg` `xl` string |       Yes |
| icon                |        `React.ReactNode`        |       Yes |
| baseStyles          |       `baseStyles object`       |       Yes |
| disabledStyles      |     `disabledStyles object`     |       Yes |
| selectedStyles      |     `selectedStyles object`     |       Yes |
| indeterminateStyles |  `indeterminateStyles object`   |       Yes |

### CheckboxGroup Props Reference

| Key         |              type               | Optional? |
| :---------- | :-----------------------------: | --------: |
| children    |        `React.ReactNode`        |        No |
| spacing     | `xs` `sm` `md` `lg` `xl` string |       Yes |
| orientation |     `verticle` `horizontal`     |       Yes |
| ref         | `RefObject<HTMLButtonElement>;` |       Yes |
| onChange    |   `(value: string[]) => void`   |       Yes |
