### ISSUE TITLE
HOV-15 | Textarea Component

### ISSUE THREAD

**Issue by Raalzz** [antstackio/hover-design#40]
## Expected Behavior
Make a `<Textarea>` Component
Features:
- Should come with default `input` props
- Inherit from `<input>`

## Current Behavior
No Textarea component

- [ ] Make spec for Textarea component
- [ ] Make the base component with API and without styles
- [ ] add styling

**Comment by pruthvi2103** [comment]
@Shadow-Flash HOV-15 is the ticket number, kindly update the PR title to fit this
