### ISSUE TITLE
HOV-16 | Divider Component

### ISSUE THREAD

**Issue by Raalzz** [antstackio/hover-design#45]
## Expected Behavior
Make a `<Divider>` Component
Features:
- Should come with default `div` props
- Inherit from `<div>`

## Current Behavior
No Divider component

- [ ] Make spec for Divider component
- [ ] Make the base component with API and without styles
- [ ] add styling

**Comment by pruthvi2103** [comment]
Please add the keyword `HOV-16` to your PR title  as its the corresponding ticket id
