### ISSUE TITLE
HOV-31 | Stepper Component

### ISSUE THREAD

**Issue by Raalzz** [antstackio/hover-design#46]
## Expected Behavior
Make a `<Stepper>` Component
Features:
- Should come with default `div` props
- Inherit from `<div>`

## Current Behavior
No Stepper component

- [ ] Make spec for Stepper component
- [ ] Make the base component with API and without styles
- [ ] add styling

**Comment by pruthvi2103** [comment]
Deprioritizing this for next release removing from https://github.com/antstackio/hover-design/milestone/3

**Comment by Raalzz** [comment]
## **Stepper and StepperStep Specs**


### StepperStep Props Reference

| Key              |       type        | Optional? |
| :--------------- | :---------------: | --------: |
| isStepClickable  |     `boolean`     |       Yes |
| isStepSelectable |     `boolean`     |       Yes |
| children         | `React.ReactNode` |       Yes |
| isLoading        |     `boolean`     |       Yes |
| showIcon         |     `boolean`     |       Yes |

### Stepper Props Reference

| Key             |              type               |  Optional? |
| :-------------- | :-----------------------------: | ---------: |
| activeStep      |            `number`             |         No |
| children        |        `React.ReactNode`        |         No |
| onStepClick     |  `(stepIndex: number) => void`  |        Yes |
| orientation     |     `verticle` `horizontal`     |        Yes |
| size            | `xs` `sm` `md` `lg` `xl` string |        Yes |
| iconPosition    |         `left` `right`          | Yes(check) |
| borderRadius    | `xs` `sm` `md` `lg` `xl` string | Yes(check) |
| baseStyles      |       `baseStyles object`       |        Yes |
| completedStyles |    `completedStyles object`     |        Yes |
| progressStyles  |     `progressStyles object`     |        Yes |

baseStyles

| Property        | Description | Default                      |
| --------------- | ----------- | ---------------------------- |
| backgroundColor | Background  | rgb(250, 250, 250)           |
| color           | Color       | rgb(204, 204, 204)           |
| border          | Border      | 2px solid rgb(204, 204, 204) |
| icon            | ReactNode   | -                            |

completedStyles

| Property        | Description | Default                      |
| --------------- | ----------- | ---------------------------- |
| backgroundColor | Background  | rgb(250, 250, 250)           |
| color           | Color       | rgb(204, 204, 204)           |
| border          | Border      | 2px solid rgb(204, 204, 204) |
| icon            | ReactNode   | -                            |

progressStyles

| Property        | Description | Default                      |
| --------------- | ----------- | ---------------------------- |
| backgroundColor | Background  | rgb(250, 250, 250)           |
| color           | Color       | rgb(204, 204, 204)           |
| border          | Border      | 2px solid rgb(204, 204, 204) |
| icon            | ReactNode   | -                            |

**Comment by Rakshith088** [comment]
@pruthvi2103 
https://www.figma.com/file/IZHRiuhZEG4GCIMpBKA7ar/Hover?node-id=1892%3A397
