### ISSUE TITLE
Table Component

### ISSUE THREAD

**Issue by Raalzz** [antstackio/hover-design#48]
## Expected Behavior
Make a `<Table>` Component
Features:
- Should come with default `table` props
- Inherit from `<table>`

## Current Behavior
No Table component

- [ ] Make spec for Table component
- [ ] Make the base component with API and without styles
- [ ] add styling

**Comment by hafsahayath** [comment]
## Table props

| Attributes     |                                                                                     Values                                                                                     | Optional? |
| :------------- | :----------------------------------------------------------------------------------------------------------------------------------------------------------------------------: | ---------: |
| children  |                                                       `ReactNode`                                                       |       No |
|border       |                                                                            `boolean`                                                                             |        Yes |
|borderColor   | `string` |        Yes |
| borderRadius |            `string`            |        Yes |
| rowHeight     |            `string`            |        Yes |
| cellPadding      |                                            `string`                                           |        Yes |
| alignHeading       |                                                                                    `left` &#124;  `right` &#124;  `center`                                                                                  |        Yes |
| alignContent     |                                                                                    `left` &#124;  `right` &#124;  `center`                                                                                    |        Yes |
| headingBackground            |                                                                  `string`                                                                  |        Yes |
| overrideTableContainerClass        |                                                                                 `string`                                                                                  |        Yes |
| overrideTableClass        |                                                                                 `string`                                                                                  |        Yes |
