### ISSUE TITLE
HOV-20 | DateTimePicker Component

### ISSUE THREAD

**Issue by Raalzz** [antstackio/hover-design#49]
## Expected Behavior
Make a `<DateTimePicker>` Component
Features:
- Should come with default `div` props
- Inherit from `<div>`

## Current Behavior
No DateTimePicker component

- [ ] Make spec for DateTimePicker component
- [ ] Make the base component with API and without styles
- [ ] add styling

**Comment by pruthvi2103** [comment]
@Shadow-Flash I see you have picked this up. Lets have a discussion on it before we start, have some potential ideas and want to know what you have in mind about them

**Comment by Shadow-Flash** [comment]
> @Shadow-Flash I see you have picked this up. Lets have a discussion on it before we start, have some potential ideas and want to know what you have in mind about them

Yeah, sure! Will discuss this on Monday in the office. If it's fine with you!

**Comment by pruthvi2103** [comment]
Yup anytime is good with me, don't burn yourself just added this as a reminder whenever you look at this :D

**Comment by pruthvi2103** [comment]
Deprioritizing this for next release removing from  https://github.com/antstackio/hover-design/milestone/2

**Comment by pruthvi2103** [comment]
Deprioritizing this for next release removing from https://github.com/antstackio/hover-design/milestone/3

**Comment by Rakshith088** [comment]
@Shadow-Flash @pruthvi2103 
https://www.figma.com/file/IZHRiuhZEG4GCIMpBKA7ar/Hover?node-id=1892%3A397

**Comment by pruthvi2103** [comment]
issue code [HOV-20](https://hoverdesign.atlassian.net/browse/HOV-20)
