### ISSUE TITLE
HOV-31 | ComboBox Component

### ISSUE THREAD

**Issue by Raalzz** [antstackio/hover-design#50]
## Expected Behavior
Make a `<ComboBox>` Component
Features:
- Should come with default `div` props
- Inherit from `<div>`

## Current Behavior
No ComboBox component

- [ ] Make spec for ComboBox component
- [ ] Make the base component with API and without styles
- [ ] add styling

**Comment by pruthvi2103** [comment]
De-Prioritizing this for https://github.com/antstackio/hover-design/milestone/2 as per our discussion

**Comment by Raalzz** [comment]
Spec for MultiSelect [V1] :

| Attributes        |              Values               | Default Value | Optional ? |
| :---------------- | :-------------------------------: | :-----------: | ---------: |
| options           |            `Options[]`            |       -       |        Yes |
| defaultValue      | `Uncontrolled input defaultValue` |       -       |        Yes |
| isDisabled        |             `boolean`             |    `false`    |        Yes |
| isClearable       |             `boolean`             |    `false`    |        Yes |
| error             |            `ReactNode`            |       -       |        Yes |
| nothingFoundLabel |            `ReactNode`            |       -       |        Yes |
| onChange          |     `(value: string) => void`     |       -       |        Yes |
| onDropdownOpen    |           `() => void`            |       -       |        Yes |
| onDropdownClose   |           `() => void`            |       -       |        Yes |
| isSearchable      |             `boolean`             |    `false`    |        Yes |

**Comment by pruthvi2103** [comment]
this has been combined into `Select`  closed by #83
